#!/usr/bin/env node
/**
 * NyayOS governance registry tool.
 *
 * Reads docs/founder/NYAYOS_STATUS_REGISTRY.json (the machine source of truth for
 * task status and dependencies), validates it against the canonical status rules,
 * and renders the derived documents:
 *
 *   docs/founder/NYAYOS_STATUS_REGISTRY.md    human view of the registry
 *   docs/founder/NYAYOS_DEPENDENCY_GRAPH.md   Mermaid dependency graph
 *   docs/founder/NYAYOS_STATUS_DASHBOARD.md   auto-generated status dashboard
 *
 * and, when the registry changed relative to a previous version, appends an
 * auto-generated entry to docs/founder/NYAYOS_CHANGELOG.md.
 *
 * Usage:
 *   node scripts/governance/registry.mjs validate
 *   node scripts/governance/registry.mjs generate [--check]
 *   node scripts/governance/registry.mjs changelog --previous <path-to-old-registry.json> [--date YYYY-MM-DD]
 *   node scripts/governance/registry.mjs all [--check]
 *
 * No dependencies. Node >= 18.
 * Rules: docs/founder/NYAYOS_CANONICAL_STATUS_RULES.md
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");
const REGISTRY = resolve(ROOT, "docs/founder/NYAYOS_STATUS_REGISTRY.json");
const OUT = {
  registryMd: resolve(ROOT, "docs/founder/NYAYOS_STATUS_REGISTRY.md"),
  graph: resolve(ROOT, "docs/founder/NYAYOS_DEPENDENCY_GRAPH.md"),
  dashboard: resolve(ROOT, "docs/founder/NYAYOS_STATUS_DASHBOARD.md"),
  changelog: resolve(ROOT, "docs/founder/NYAYOS_CHANGELOG.md"),
};

const STATUS_FLOW = ["OPEN", "IN_PROGRESS", "REVIEW", "CANONICAL", "SUPERSEDED"];
const ACTIVE_OR_LATER = new Set(["IN_PROGRESS", "REVIEW", "CANONICAL"]);
const ID_RE = /^A-\d{3}(-R\d?)?$/; // optional remediation suffix, e.g. A-033-R

const GENERATED_BANNER = (source) =>
  `<!-- AUTO-GENERATED by scripts/governance/registry.mjs from ${source}. DO NOT EDIT BY HAND. Edit the registry JSON and run: node scripts/governance/registry.mjs generate -->`;

// ---------------------------------------------------------------------------
// Load
// ---------------------------------------------------------------------------

function loadRegistry(path = REGISTRY) {
  const raw = readFileSync(path, "utf8");
  const data = JSON.parse(raw);
  if (!Array.isArray(data.tasks)) throw new Error("registry.tasks must be an array");
  return data;
}

// ---------------------------------------------------------------------------
// Validate
// ---------------------------------------------------------------------------

function validate(reg) {
  const errors = [];
  const warnings = [];
  const byId = new Map();

  for (const t of reg.tasks) {
    if (!ID_RE.test(t.id ?? "")) errors.push(`${t.id ?? "?"}: id must match A-nnn or A-nnn-R`);
    if (byId.has(t.id)) errors.push(`${t.id}: duplicate id`);
    byId.set(t.id, t);
  }

  for (const t of reg.tasks) {
    const tag = t.id;
    if (!t.title) errors.push(`${tag}: title required`);
    if (!STATUS_FLOW.includes(t.status)) errors.push(`${tag}: status "${t.status}" not in ${STATUS_FLOW.join(" → ")}`);
    if (!Array.isArray(t.inputs)) errors.push(`${tag}: inputs must be an array`);
    if (!Array.isArray(t.planned_inputs)) errors.push(`${tag}: planned_inputs must be an array`);
    if (!Array.isArray(t.outputs)) errors.push(`${tag}: outputs must be an array`);

    // RULE 1 — inputs must be CANONICAL. No exceptions, any status.
    for (const dep of t.inputs ?? []) {
      const d = byId.get(dep);
      if (!d) errors.push(`${tag}: input ${dep} does not exist`);
      else if (d.status !== "CANONICAL")
        errors.push(`${tag}: input ${dep} is ${d.status} — only CANONICAL tasks may be inputs`);
    }

    // RULE 2 — planned_inputs may be non-canonical, but a task that has started
    // (IN_PROGRESS or later) may not carry unresolved planned inputs.
    for (const dep of t.planned_inputs ?? []) {
      const d = byId.get(dep);
      if (!d) errors.push(`${tag}: planned_input ${dep} does not exist`);
      else if (d.status === "CANONICAL")
        warnings.push(`${tag}: planned_input ${dep} is already CANONICAL — promote it to inputs`);
    }
    if (ACTIVE_OR_LATER.has(t.status) && (t.planned_inputs ?? []).length > 0)
      errors.push(`${tag}: status ${t.status} but planned_inputs unresolved: ${t.planned_inputs.join(", ")}`);

    // RULE 3 — CANONICAL requires evidence and at least one output.
    if (t.status === "CANONICAL") {
      if (!t.evidence) errors.push(`${tag}: CANONICAL requires evidence`);
      if ((t.outputs ?? []).length === 0) errors.push(`${tag}: CANONICAL requires at least one output`);
    }

    // RULE 4 — SUPERSEDED must name its successor.
    if (t.status === "SUPERSEDED") {
      if (!t.superseded_by) errors.push(`${tag}: SUPERSEDED requires superseded_by`);
      else if (!byId.has(t.superseded_by)) errors.push(`${tag}: superseded_by ${t.superseded_by} does not exist`);
    } else if (t.superseded_by) {
      errors.push(`${tag}: superseded_by set but status is ${t.status}`);
    }

    // RULE 5 — evidence and non-external outputs must exist in the repository.
    const pathsToCheck = [t.evidence, ...(t.outputs ?? [])].filter(
      (p) => p && !p.startsWith("external:"),
    );
    for (const p of pathsToCheck) {
      if (!existsSync(resolve(ROOT, p))) {
        (t.status === "CANONICAL" ? errors : warnings).push(`${tag}: path not found: ${p}`);
      }
    }
  }

  // RULE 6 — no cycles across inputs + planned_inputs.
  const state = new Map();
  const visit = (id, stack) => {
    if (state.get(id) === "done") return;
    if (state.get(id) === "visiting") {
      errors.push(`cycle: ${[...stack, id].join(" → ")}`);
      return;
    }
    state.set(id, "visiting");
    const t = byId.get(id);
    for (const dep of [...(t?.inputs ?? []), ...(t?.planned_inputs ?? [])]) {
      if (byId.has(dep)) visit(dep, [...stack, id]);
    }
    state.set(id, "done");
  };
  for (const t of reg.tasks) visit(t.id, []);

  return { errors, warnings };
}

// ---------------------------------------------------------------------------
// Render helpers
// ---------------------------------------------------------------------------

const STATUS_ICON = {
  OPEN: "○",
  IN_PROGRESS: "◐",
  REVIEW: "◑",
  CANONICAL: "●",
  SUPERSEDED: "⊘",
};

function today() {
  return new Date().toISOString().slice(0, 10);
}

function esc(s) {
  return String(s ?? "").replace(/\|/g, "\\|").replace(/\n/g, " ");
}

function linkPath(p) {
  if (!p) return "—";
  if (p.startsWith("external:")) return `*${p.slice(9)}* (external)`;
  // docs/founder/*.md is where the rendered files live; make links relative to it
  const rel = p.startsWith("docs/founder/") ? p.slice("docs/founder/".length) : `../../${p}`;
  return `[${p}](${rel})`;
}

// ---------------------------------------------------------------------------
// Render: registry (human view)
// ---------------------------------------------------------------------------

function renderRegistryMd(reg) {
  const rows = reg.tasks
    .map(
      (t) =>
        `| ${t.id} | ${esc(t.title)} | ${STATUS_ICON[t.status]} **${t.status}** | ${esc(t.owner)} | ${esc(t.tool)} | ${t.gate ? esc(t.gate) : "—"} | ${(t.inputs ?? []).join(", ") || "—"} | ${(t.planned_inputs ?? []).join(", ") || "—"} | ${t.evidence ? linkPath(t.evidence) : "—"} | ${t.updated} |`,
    )
    .join("\n");

  return `${GENERATED_BANNER("NYAYOS_STATUS_REGISTRY.json")}
# NYAYOS STATUS REGISTRY

**Source of truth:** [\`NYAYOS_STATUS_REGISTRY.json\`](NYAYOS_STATUS_REGISTRY.json) · **Rules:** [NYAYOS_CANONICAL_STATUS_RULES.md](NYAYOS_CANONICAL_STATUS_RULES.md) · **Registry version:** ${reg.version} · **Updated:** ${reg.updated}

Status flow: \`OPEN → IN_PROGRESS → REVIEW → CANONICAL → SUPERSEDED\`
Legend: ○ OPEN · ◐ IN_PROGRESS · ◑ REVIEW · ● CANONICAL · ⊘ SUPERSEDED

**The rule:** a task may list another task under \`inputs\` **only if that task is CANONICAL.** Future dependencies go under \`planned_inputs\` and block the task from moving past OPEN. Enforced by \`task-gate\` on every push and pull request.

| ID | Title | Status | Owner | Tool / mode | Gate | Inputs (canonical) | Planned inputs | Evidence | Updated |
|---|---|---|---|---|---|---|---|---|---|
${rows}

## Notes

${reg.tasks
  .filter((t) => t.notes)
  .map((t) => `- **${t.id}** — ${esc(t.notes)}`)
  .join("\n")}
`;
}

// ---------------------------------------------------------------------------
// Render: dependency graph (Mermaid)
// ---------------------------------------------------------------------------

function renderGraph(reg) {
  const nodeId = (id) => id.replaceAll("-", "_");
  const lines = ["flowchart LR"];

  const byStatus = {};
  for (const t of reg.tasks) (byStatus[t.status] ??= []).push(t);

  for (const s of STATUS_FLOW) {
    if (!byStatus[s]) continue;
    lines.push(`  subgraph ${s}`);
    for (const t of byStatus[s]) {
      const label = `${t.id}<br/>${t.title.replace(/"/g, "'").slice(0, 44)}${t.title.length > 44 ? "…" : ""}`;
      lines.push(`    ${nodeId(t.id)}["${label}"]`);
    }
    lines.push("  end");
  }

  for (const t of reg.tasks) {
    for (const dep of t.inputs ?? []) lines.push(`  ${nodeId(dep)} --> ${nodeId(t.id)}`);
    for (const dep of t.planned_inputs ?? []) lines.push(`  ${nodeId(dep)} -. planned .-> ${nodeId(t.id)}`);
  }

  lines.push("");
  lines.push("  classDef OPEN fill:#f3f4f6,stroke:#6b7280,color:#111827;");
  lines.push("  classDef IN_PROGRESS fill:#dbeafe,stroke:#2563eb,color:#111827;");
  lines.push("  classDef REVIEW fill:#fef3c7,stroke:#d97706,color:#111827;");
  lines.push("  classDef CANONICAL fill:#dcfce7,stroke:#16a34a,color:#111827;");
  lines.push("  classDef SUPERSEDED fill:#e5e7eb,stroke:#9ca3af,color:#6b7280,stroke-dasharray: 4 2;");
  for (const s of STATUS_FLOW) {
    if (byStatus[s]) lines.push(`  class ${byStatus[s].map((t) => nodeId(t.id)).join(",")} ${s};`);
  }

  const canonicalCount = (byStatus.CANONICAL ?? []).length;
  const blocked = reg.tasks.filter((t) => (t.planned_inputs ?? []).length > 0);

  return `${GENERATED_BANNER("NYAYOS_STATUS_REGISTRY.json")}
# NYAYOS DEPENDENCY GRAPH

**Source:** [\`NYAYOS_STATUS_REGISTRY.json\`](NYAYOS_STATUS_REGISTRY.json) · **Generated:** ${today()} · **Tasks:** ${reg.tasks.length} · **Canonical:** ${canonicalCount}

Solid arrows are **inputs** — always CANONICAL, enforced. Dashed arrows are **planned inputs** — dependencies that are not yet canonical; a task carrying any dashed arrow **may not leave OPEN**.

\`\`\`mermaid
${lines.join("\n")}
\`\`\`

## Blocked tasks — waiting on non-canonical inputs

${
  blocked.length === 0
    ? "_None._"
    : `| Task | Waiting on | Those tasks are |\n|---|---|---|\n${blocked
        .map((t) => {
          const waits = t.planned_inputs.map((d) => {
            const dep = reg.tasks.find((x) => x.id === d);
            return `${d} (${dep ? dep.status : "missing"})`;
          });
          return `| **${t.id}** ${esc(t.title)} | ${t.planned_inputs.join(", ")} | ${waits.join(", ")} |`;
        })
        .join("\n")}`
}

## Critical path to production

\`\`\`
A-018 Sprint 1.1 State Completion  ─►  A-015 Sprint 2 Fact Cards  ─┐
A-008 Figma V2                      ────────────────────────────────┤
A-009 User interviews + WTP        ────────────────────────────────┼─►  A-012 Production (FA-002)
A-010 Security + data review       ────────────────────────────────┘
\`\`\`

Production (A-012) has **no canonical inputs yet**; every arrow into it is dashed. That is the graph saying what the Founder Authorization Record says: FA-002 is not grantable today.
`;
}

// ---------------------------------------------------------------------------
// Render: status dashboard (auto)
// ---------------------------------------------------------------------------

function renderDashboard(reg) {
  const count = (s) => reg.tasks.filter((t) => t.status === s).length;
  const active = reg.tasks.filter((t) => ["IN_PROGRESS", "REVIEW"].includes(t.status));
  const ready = reg.tasks.filter(
    (t) => t.status === "OPEN" && (t.planned_inputs ?? []).length === 0,
  );
  const blocked = reg.tasks.filter((t) => t.status === "OPEN" && (t.planned_inputs ?? []).length > 0);
  const canonical = reg.tasks.filter((t) => t.status === "CANONICAL");
  const recent = [...reg.tasks].sort((a, b) => (a.updated < b.updated ? 1 : -1)).slice(0, 8);

  const row = (t) =>
    `| ${t.id} | ${esc(t.title)} | ${STATUS_ICON[t.status]} ${t.status} | ${esc(t.owner)} | ${t.gate ? esc(t.gate) : "—"} | ${t.updated} |`;
  const table = (list) =>
    list.length === 0
      ? "_None._"
      : `| ID | Title | Status | Owner | Gate | Updated |\n|---|---|---|---|---|---|\n${list.map(row).join("\n")}`;

  return `${GENERATED_BANNER("NYAYOS_STATUS_REGISTRY.json")}
# NYAYOS STATUS DASHBOARD (auto-generated)

**Generated:** ${today()} from registry v${reg.version} (updated ${reg.updated}).
This is the **machine view**. The founder's curated view — north stars, phase, risks, next actions — is [NYAYOS_FOUNDER_DASHBOARD.md](NYAYOS_FOUNDER_DASHBOARD.md). Gates are governed by [NYAYOS_FOUNDER_AUTHORIZATION_RECORD.md](NYAYOS_FOUNDER_AUTHORIZATION_RECORD.md). If this page and either of those disagree, they win.

## Counts

| ○ OPEN | ◐ IN_PROGRESS | ◑ REVIEW | ● CANONICAL | ⊘ SUPERSEDED | Total |
|---:|---:|---:|---:|---:|---:|
| ${count("OPEN")} | ${count("IN_PROGRESS")} | ${count("REVIEW")} | ${count("CANONICAL")} | ${count("SUPERSEDED")} | ${reg.tasks.length} |

## In flight

${table(active)}

## Ready to start — all inputs canonical, nothing planned outstanding

${table(ready)}

## Blocked — waiting on non-canonical inputs

${
  blocked.length === 0
    ? "_None._"
    : `| ID | Title | Waiting on | Owner |\n|---|---|---|---|\n${blocked
        .map((t) => `| ${t.id} | ${esc(t.title)} | ${t.planned_inputs.join(", ")} | ${esc(t.owner)} |`)
        .join("\n")}`
}

## Canonical

${table(canonical)}

## Recently updated

${table(recent)}

---
Regenerate: \`node scripts/governance/registry.mjs generate\` · Validate: \`node scripts/governance/registry.mjs validate\` · Graph: [NYAYOS_DEPENDENCY_GRAPH.md](NYAYOS_DEPENDENCY_GRAPH.md) · Registry: [NYAYOS_STATUS_REGISTRY.md](NYAYOS_STATUS_REGISTRY.md)
`;
}

// ---------------------------------------------------------------------------
// Changelog: diff two registries and append an auto entry
// ---------------------------------------------------------------------------

function diffRegistries(prev, next) {
  const prevById = new Map(prev.tasks.map((t) => [t.id, t]));
  const nextById = new Map(next.tasks.map((t) => [t.id, t]));
  const added = [];
  const transitions = [];
  const removed = [];
  for (const t of next.tasks) {
    const p = prevById.get(t.id);
    if (!p) added.push(t);
    else if (p.status !== t.status) transitions.push({ id: t.id, title: t.title, from: p.status, to: t.status });
  }
  for (const t of prev.tasks) if (!nextById.has(t.id)) removed.push(t);
  return { added, transitions, removed };
}

function renderChangelogEntry(diff, date) {
  const parts = [`## ${date} — [auto] Status registry changes`, ""];
  if (diff.transitions.length) {
    parts.push("### Status transitions", "", "| Task | From | To |", "|---|---|---|");
    for (const t of diff.transitions) parts.push(`| **${t.id}** ${esc(t.title)} | ${t.from} | **${t.to}** |`);
    parts.push("");
  }
  if (diff.added.length) {
    parts.push("### New tasks", "");
    for (const t of diff.added) parts.push(`- **${t.id}** — ${esc(t.title)} · ${t.status} · owner: ${esc(t.owner)}`);
    parts.push("");
  }
  if (diff.removed.length) {
    parts.push("### Removed tasks", "");
    for (const t of diff.removed) parts.push(`- **${t.id}** — ${esc(t.title)}`);
    parts.push("");
  }
  parts.push("_Generated by `scripts/governance/registry.mjs changelog` from `NYAYOS_STATUS_REGISTRY.json`._", "", "---", "");
  return parts.join("\n");
}

function appendChangelog(entry) {
  const md = readFileSync(OUT.changelog, "utf8");
  // Insert before the first "## " heading so newest stays first, after the header block.
  const idx = md.search(/^## /m);
  const updated = idx === -1 ? md + "\n" + entry : md.slice(0, idx) + entry + "\n" + md.slice(idx);
  writeFileSync(OUT.changelog, updated, "utf8");
}

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------

function writeOrCheck(path, content, check) {
  const current = existsSync(path) ? readFileSync(path, "utf8") : null;
  // Ignore the generated-date line when checking, so a re-run on another day is not "stale".
  const norm = (s) => (s ?? "").replace(/\*\*Generated:\*\* \d{4}-\d{2}-\d{2}/g, "**Generated:** DATE");
  if (check) {
    if (norm(current) !== norm(content)) return false;
    return true;
  }
  writeFileSync(path, content, "utf8");
  return true;
}

function main() {
  const [cmd = "all", ...rest] = process.argv.slice(2);
  const flags = new Set(rest.filter((a) => a.startsWith("--")));
  const opt = (name) => {
    const i = rest.indexOf(name);
    return i >= 0 ? rest[i + 1] : undefined;
  };
  const check = flags.has("--check");

  const reg = loadRegistry();

  if (cmd === "validate" || cmd === "all") {
    const { errors, warnings } = validate(reg);
    for (const w of warnings) console.log(`WARN  ${w}`);
    for (const e of errors) console.error(`ERROR ${e}`);
    console.log(`validate: ${reg.tasks.length} tasks · ${errors.length} error(s) · ${warnings.length} warning(s)`);
    if (errors.length) process.exit(1);
  }

  if (cmd === "generate" || cmd === "all") {
    const results = [
      ["registry.md", writeOrCheck(OUT.registryMd, renderRegistryMd(reg), check)],
      ["dependency graph", writeOrCheck(OUT.graph, renderGraph(reg), check)],
      ["status dashboard", writeOrCheck(OUT.dashboard, renderDashboard(reg), check)],
    ];
    let stale = false;
    for (const [name, ok] of results) {
      console.log(`${check ? (ok ? "fresh " : "STALE ") : "wrote "}${name}`);
      if (!ok) stale = true;
    }
    if (check && stale) {
      console.error("generated documents are out of date — run: node scripts/governance/registry.mjs generate");
      process.exit(1);
    }
  }

  if (cmd === "changelog") {
    const prevPath = opt("--previous");
    if (!prevPath) {
      console.error("changelog requires --previous <old-registry.json>");
      process.exit(2);
    }
    const prev = JSON.parse(readFileSync(prevPath, "utf8"));
    const diff = diffRegistries(prev, reg);
    if (!diff.transitions.length && !diff.added.length && !diff.removed.length) {
      console.log("changelog: no status changes");
      return;
    }
    const entry = renderChangelogEntry(diff, opt("--date") ?? today());
    if (check) {
      console.log(entry);
    } else {
      appendChangelog(entry);
      console.log(`changelog: appended ${diff.transitions.length} transition(s), ${diff.added.length} new, ${diff.removed.length} removed`);
    }
  }
}

main();
